/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2022-02-13 20:25:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class product_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("        <title>Shop Here</title>\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                margin: 0;\n");
      out.write("                background:#71797E ;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("ul.sidenav {\n");
      out.write("  list-style-type: none;\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  width: 25%;\n");
      out.write("  color:#ccc;\n");
      out.write("  background-color:#404541;\n");
      out.write("  position: fixed;\n");
      out.write("  height: 100%;\n");
      out.write("  overflow: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sidenav li a {\n");
      out.write("  display: block;\n");
      out.write("  color: #ccc;\n");
      out.write("  padding: 8px 16px;\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("ul.sidenav li a.active {\n");
      out.write("  background-color: #ACCFBF;\n");
      out.write("  color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.sidenav li a:hover:not(.active) {\n");
      out.write("  background-color: #555;\n");
      out.write("  color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.content {\n");
      out.write("  margin-left: 25%;\n");
      out.write("  padding: 1px 16px;\n");
      out.write("  height: 1000px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 900px) {\n");
      out.write("  ul.sidenav {\n");
      out.write("    width: 100%;\n");
      out.write("    height: auto;\n");
      out.write("    position: relative;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  ul.sidenav li a {\n");
      out.write("    float: left;\n");
      out.write("    padding: 15px;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  div.content {margin-left: 0;}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 400px) {\n");
      out.write("  ul.sidenav li a {\n");
      out.write("    text-align: center;\n");
      out.write("    float: none;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("            .button {\n");
      out.write("  background-color: #4CAF50; /* Green */\n");
      out.write("  border: none;\n");
      out.write("  color: white;\n");
      out.write("  padding: 16px 32px;\n");
      out.write("  text-align: center;\n");
      out.write("  text-decoration: none;\n");
      out.write("  display: inline-block;\n");
      out.write("  font-size: 16px;\n");
      out.write("  margin: 4px 2px;\n");
      out.write("  transition-duration: 0.4s;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write(".button2 {\n");
      out.write("  background-color: white; \n");
      out.write("  color: black; \n");
      out.write("  border: 2px solid #abb0ac;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button2:hover {\n");
      out.write("  background-color: #abb0ac;\n");
      out.write("  color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("            body {\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box {\n");
      out.write("  background-color: transparent;\n");
      out.write("  width: 300px;\n");
      out.write("  height: 200px;\n");
      out.write("  border: 1px solid #f1f1f1;\n");
      out.write("  perspective: 1000px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box-inner {\n");
      out.write("  position: relative;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  text-align: center;\n");
      out.write("  transition: transform 0.8s;\n");
      out.write("  transform-style: preserve-3d;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box:hover .flip-box-inner {\n");
      out.write("  transform: rotateY(180deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box-front, .flip-box-back {\n");
      out.write("  position: absolute;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  -webkit-backface-visibility: hidden;\n");
      out.write("  backface-visibility: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box-front {\n");
      out.write("  background-color: #bbb;\n");
      out.write("  color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flip-box-back {\n");
      out.write("  background-color: #404541;\n");
      out.write("  color: white;\n");
      out.write("  transform: rotateY(180deg);\n");
      out.write("}\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            if(!!window.performance && window.performance.navigation.type == 2)\n");
      out.write("            {\n");
      out.write("                window.location.reload(true);\n");
      out.write("            }\n");
      out.write("         </script>\n");
      out.write("       \n");
      out.write("        ");

if(session.getAttribute("user_name")==null)
{
    response.sendRedirect("login.html");
}

else{

      out.write("\n");
      out.write("\n");
      out.write("        <ul class=\"sidenav\">\n");
      out.write("  <li><a  href=\"index.jsp\">Home</a></li>\n");
      out.write("  <li><a class=\"active\" href=\"product_view.jsp\">Shop Here</a></li>\n");
      out.write("  <li><a href=\"view_cart.jsp\">Cart</a></li>\n");
      out.write("  <li><a href=\"history.jsp\">Order History</a></li>\n");
      out.write("  <li><a href=\"feedback.html\">Feedback</a></li>\n");
      out.write("  <li><a href=\"appointment.html\">Appointment</a></li>\n");
      out.write("  <li><a href=\"logout.jsp\">Logout</a></li>\n");
      out.write("</ul>\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <h1>PRODUCT LIST</h1>\n");
      out.write("        ");

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/products","root","");
            Statement st=c.createStatement();
            ResultSet rs=st.executeQuery("select * from stocks");
            out.println("<table border=0 align='center' cellspacing=40 cellpadding=40><tr>");
            int i=0;
            while(rs.next())
            {
                String mn=rs.getString(2);
                String sp=rs.getString(4);
                out.println("<td>"+ "<div class='flip-box'><div class='flip-box-inner'><div class='flip-box-front'><form action='cart.jsp' method='post'><img src='"+rs.getString(6)+"' width=298 height=198></div>"
                        + " <div class='flip-box-back'>Company :"+ rs.getString(1)+"<hr><br>Model Name:"+mn+"<input type='hidden' name='model' value='"+mn+"'><br>Price :"+sp+"<input type='hidden' name='price' value='"+sp+"'><hr>Description :"+rs.getString(7)+"<hr>"
                        + "Enter Quantity :<input type='number' value='1' id='qt' name='qt1'><hr><button class='button button2'>Add To Cart <i class='fa fa-shopping-cart'></i></button></form></div></div></div></td>");
                i++;
                if(i%2==0)
                {
                    out.println("</tr><tr>");
                }
            }
            out.println("</table>");
        }catch(Exception e){out.println(e);}
        
      out.write("\n");
      out.write("        </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
