/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2022-02-14 03:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class view_005fcart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("        <style>\n");
      out.write("            \n");
      out.write("            body {\n");
      out.write("                background:#ACCFBF;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .right {\n");
      out.write("                top:10px;\n");
      out.write("                position:absolute;\n");
      out.write("                left:1250px;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            right1 {\n");
      out.write("                top:5px;\n");
      out.write("                left:500px;\n");
      out.write("                position:absolute;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            .button {\n");
      out.write("  background-color: #4CAF50; /* Green */\n");
      out.write("  border: none;\n");
      out.write("  color: white;\n");
      out.write("  padding: 16px 32px;\n");
      out.write("  text-align: center;\n");
      out.write("  text-decoration: none;\n");
      out.write("  display: inline-block;\n");
      out.write("  font-size: 16px;\n");
      out.write("  margin: 4px 2px;\n");
      out.write("  transition-duration: 0.4s;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write(".button2 {\n");
      out.write("  background-color: white; \n");
      out.write("  color: black; \n");
      out.write("  border: 2px solid #abb0ac;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button2:hover {\n");
      out.write("  background-color: #abb0ac;\n");
      out.write("  color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("            body {\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("body {margin: 0;}\n");
      out.write("\n");
      out.write("ul.topnav {\n");
      out.write("  list-style-type: none;\n");
      out.write("  margin: 0;\n");
      out.write("  padding: 0;\n");
      out.write("  overflow: hidden;\n");
      out.write("  background-color: #333;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.topnav li {float: left;}\n");
      out.write("\n");
      out.write("ul.topnav li a {\n");
      out.write("  display: block;\n");
      out.write("  color: white;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 14px 16px;\n");
      out.write("  text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul.topnav li a:hover:not(.active) {background-color: #838585;}\n");
      out.write("\n");
      out.write("ul.topnav li a.active {background-color: #838585;}\n");
      out.write("\n");
      out.write("ul.topnav li.right {float: right;}\n");
      out.write("\n");
      out.write("@media screen and (max-width: 600px) {\n");
      out.write("  ul.topnav li.right, \n");
      out.write("  ul.topnav li {float: none;}\n");
      out.write("}\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            function incr(i,price)\n");
      out.write("            {\n");
      out.write("                \n");
      out.write("                var qty=document.getElementById(\"qt\"+i).innerHTML; \n");
      out.write("                var cid=document.getElementById(\"cid\"+i).value;\n");
      out.write("                var cid1=document.getElementById(\"cid\"+i).value;\n");
      out.write("               \n");
      out.write("                 if(Number(qty)<5)\n");
      out.write("                 {\n");
      out.write("                  \n");
      out.write("                 \n");
      out.write("                    \n");
      out.write("                    qty=Number(qty)+1;\n");
      out.write("                    var p=Number(qty)*Number(price);\n");
      out.write("                    document.getElementById(\"total\"+i).innerHTML=p;\n");
      out.write("                    document.getElementById(\"qt\"+i).innerHTML=qty;\n");
      out.write("                    var xhttp = new XMLHttpRequest();\n");
      out.write("                    xhttp.onreadystatechange = function() \n");
      out.write("                    {\n");
      out.write("                        if (this.readyState == 4 && this.status == 200) \n");
      out.write("                        {\n");
      out.write("                            document.getElementById(\"output\").innerHTML = this.responseText;\n");
      out.write("                        }\n");
      out.write("                    };\n");
      out.write("                    xhttp.open(\"GET\", \"modify_qty_total.jsp?q=\"+qty+\"&t=\"+p+\"&cart=\"+cid1, true);\n");
      out.write("                    xhttp.send();\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                var tot=document.getElementById(\"tt\").value;\n");
      out.write("                var gt=0;\n");
      out.write("                for(var x=1; x<=tot;x++ )\n");
      out.write("                {\n");
      out.write("                    gt+=Number(document.getElementById(\"total\"+x).innerHTML);\n");
      out.write("                }\n");
      out.write("                document.getElementById(\"grand_total\").innerHTML=gt;\n");
      out.write("            }\n");
      out.write("            }\n");
      out.write("            function decr(i,price)\n");
      out.write("            {\n");
      out.write("                var qty=document.getElementById(\"qt\"+i).innerHTML;\n");
      out.write("                var cid=document.getElementById(\"cid\"+i).value;\n");
      out.write("                \n");
      out.write("                if(Number(qty)>1)\n");
      out.write("                {\n");
      out.write("                    qty=Number(qty)-1;\n");
      out.write("                    var p=Number(qty)*Number(price);\n");
      out.write("                    document.getElementById(\"total\"+i).innerHTML=p;\n");
      out.write("                    document.getElementById(\"qt\"+i).innerHTML=qty;     \n");
      out.write("                    var xhttp = new XMLHttpRequest();\n");
      out.write("                    xhttp.onreadystatechange = function() \n");
      out.write("                    {\n");
      out.write("                        if (this.readyState == 4 && this.status == 200) \n");
      out.write("                        {\n");
      out.write("                            document.getElementById(\"output\").innerHTML = this.responseText;\n");
      out.write("                         }\n");
      out.write("                    };\n");
      out.write("                    xhttp.open(\"GET\", \"modify_qty_total.jsp?q=\"+qty+\"&t=\"+p+\"&cart=\"+cid, true);\n");
      out.write("                    xhttp.send();\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    var tot=document.getElementById(\"tt\").value;\n");
      out.write("                var gt=0;\n");
      out.write("                for(var x=1; x<=tot;x++ )\n");
      out.write("                {\n");
      out.write("                    gt+=Number(document.getElementById(\"total\"+x).innerHTML);\n");
      out.write("                }\n");
      out.write("                document.getElementById(\"grand_total\").innerHTML=gt;\n");
      out.write("            \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <script>\n");
      out.write("            if(!!window.performance && window.performance.navigation.type == 2)\n");
      out.write("            {\n");
      out.write("                window.location.reload(true);\n");
      out.write("            }\n");
      out.write("         </script>\n");
      out.write("         \n");
      out.write("         \n");
      out.write("        \n");
      out.write("        <ul class=\"topnav\">\n");
      out.write("  <li><a  href=\"index.jsp\">Home</a></li>\n");
      out.write("  <li><a href=\"product_view.jsp\">Product</a></li>\n");
      out.write("  <li><a class=\"active\" href=\"view_cart.jsp\">View Cart</a></li>\n");
      out.write("  <li class=\"right\" style=\"color: white\">Welcome ");
      out.print(session.getAttribute("user_name"));
      out.write("</li>\n");
      out.write("  <li class=\"right1\"><a href=\"logout.jsp\">Logout</a></li>\n");
      out.write("</ul>\n");
      out.write("        <div style=\"padding:0 16px;\"><br><br>\n");
      out.write("            <h2 align=\"center\">Cart Details</h2>\n");
      out.write("        ");

            
        try{
            
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/products","root","");
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/products","root","");
            Statement st=c.createStatement();
            ResultSet rs=st.executeQuery("select cart.cart_id,cart.Model_Name,cart.Quantity,cart.Selling_Price,cart.Total,stocks.Company_Name,stocks.Product_img from cart,stocks where cart.Model_Name=stocks.Model_Name and cart.status='NO' and cart.username='"+session.getAttribute("user_name")+"'");
           
           out.println("<table border=1 align='center' cellspacing=20 cellpadding=20><tr><td>Sr. No</td><td>Product Image</td><td>Company Name</td><td>Model Name</td><td>Quantity</td><td>Price</td><td>Total Price</td><td>Action</td></tr>");
            int i=1;
            int gt=0;
            while(rs.next())
            {
                int cartid=rs.getInt(1);
                String modname=rs.getString(2);
                session.setAttribute("mdname",modname);
                int t=Integer.parseInt(rs.getString(5));
                
                int quantity=Integer.parseInt(rs.getString(3));
                session.setAttribute("qty",quantity);
                int price=rs.getInt(4);
                gt=gt+t;
                session.setAttribute("tot",gt);
                out.println("<tr><td>"+i+"</td><td><img src='"+rs.getString(7)+"' width=100 height=100></td><td>"+rs.getString(6)+"</td><td>"+modname+"</td><td><div id='qt"+i+"'>"+quantity+"</div><hr><div><input type='button' value='-' id='dec' onclick='decr("+i+","+price+")'>&nbsp;&nbsp;&nbsp;<input type='button' value='+' id='inc' onclick='incr("+i+","+price+")'></div></td><td>"+price+"</td><td><div id='total"+i+"'>"+t+"</div></td><td><form action='removecart.jsp' method='POST'><input type='hidden' value='"+cartid+"' name='cid' id='cid"+i+"'><button class='button button2'>Remove <i class='fa fa-trash-o'></i></button></form></td></tr>");
                i++;
            }
            out.println("<input type='hidden' id='tt' value="+(i-1)+">");
            out.println("<tr><td colspan=6>Grand Total</td><td><div id='grand_total'>"+gt+"</div></td><td><a href='product_view.jsp'><input type='submit' class='button button2' name='add_more' value='Add More Items'></a></td></tr><table>");
        }catch(Exception e){out.println(e);}
        
      out.write("\n");
      out.write("        <br><hr><br>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"output\">\n");
      out.write("            <h2 align=\"center\">Delivery Details</h2>\n");
      out.write("            <form action=\"place_order.jsp\" method=\"POST\">\n");
      out.write("            <table border=\"1\" align=\"center\">\n");
      out.write("                <tr><td>Enter Email :</td><td><input type='email' name=\"email\"></td></tr>\n");
      out.write("                <tr><td>Enter Receiver Name :</td><td><input type='text' name=\"rec_name\"></td></tr>\n");
      out.write("                <tr><td>Enter Receiver Address :</td><td> <textarea rows=\"3\" cols=\"30\" name=\"rec_add\"> </textarea>  </td></tr>\n");
      out.write("                <tr><td>Enter Mobile No :</td><td> <input type='text' name='mob_no'></td></tr>\n");
      out.write("                <tr><td>Payment Mode:</td><td><label>COD(only)</label></td></tr>\n");
      out.write("                <tr><td colspan=\"2\" align='center'><input type='submit' class='button button2' name='save1' value=\"Place Order\"></td></tr>\n");
      out.write("            </table>\n");
      out.write("            </form>     \n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
